### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by imlun** [xiaokaike/vue-qrcode#1]
`import Qrcode from 'vue-qrcode'` 后 <qrcode val="http://baidu.com"></qrcode> 报错

**Comment by xiaokaike** [comment]
@imlun  错误是什么能截图或贴代码么？

**Comment by imlun** [comment]
![image](https://cloud.githubusercontent.com/assets/14075972/16752536/b7bc7234-4814-11e6-8cf7-c0a84c843ff4.png)
![image](https://cloud.githubusercontent.com/assets/14075972/16752548/cdc8ba24-4814-11e6-8207-284db4567c73.png)
![image](https://cloud.githubusercontent.com/assets/14075972/16752562/e150cc62-4814-11e6-9619-6658e55dc30f.png)
还是说我不能这样引用

**Comment by xiaokaike** [comment]
你尝试  import Qrcode from 'vue-qrcode/src/Qrcode.vue'

**Comment by imlun** [comment]
@xiaokaike 这方法解决了。谢谢
