### ISSUE TITLE
npm 包还维护吗？或者可以考虑转让吗？

### ISSUE THREAD

**Issue by JounQin** [xiaokaike/vue-qrcode#11]
@xiaokaike 我看这个 npm 包已经两三年没维护了，如果可以的话希望可以使用这个包名，不至于让这个挺好的名字浪费了。

如有冒犯，请见谅。

**Comment by xiaokaike** [comment]
OK

**Comment by JounQin** [comment]
@xiaokaike 好的，谢谢，我的 npm username 是 jounqin ，感谢。

**Comment by xiaokaike** [comment]
done

**Comment by JounQin** [comment]
@xiaokaike 如果可以继承项目最好不过了，本来没好意思问。

**Comment by JounQin** [comment]
@xiaokaike 你好 Git 仓库还转让吗？如果不转让了我可以提个 deprecated 的 PR，避免造成误解。

**Comment by xiaokaike** [comment]
可以了转让了

**Comment by JounQin** [comment]
@xiaokaike 感谢
