### ISSUE TITLE
组件为何不将canvas转为img

### ISSUE THREAD

**Issue by keepgoingwm** [xiaokaike/vue-qrcode#5]
请问，
该组件为何不使用canvas.toDataURL()将canvas转为img，方便类似微信“长按识别二维码”的功能
（canvas无法长按识别）

**Comment by xiaokaike** [comment]
明白 可以做些支持

**Comment by keepgoingwm** [comment]
@xiaokaike OK, thanks!

**Comment by JounQin** [comment]
@keepgoingwm Please upgrade to `0.2.0`, which is a complete rewrite from scratch, which supports `Vue@2.0` and displays `img` tag.

Online DEMO: https://rx-vue.now.sh
