### ISSUE TITLE
支付vue2.0吗？

### ISSUE THREAD

**Issue by NinjaJin** [xiaokaike/vue-qrcode#7]
支持vue2.0吗？

**Comment by xiaokaike** [comment]
不支付

**Comment by xiaokaike** [comment]
https://github.com/xiaokaike/vue-qrcode/issues/3

**Comment by JounQin** [comment]
@NinjaJin Please upgrade to 0.2.0, which is a complete rewrite from scratch, which supports `Vue@2.0`.

Online DEMO: https://rx-vue.now.sh
