### ISSUE TITLE
how can i redrew the code image when the code is changing?

### ISSUE THREAD

**Issue by goldenfreemanchina** [xiaokaike/vue-qrcode#9]
RT...

**Comment by goldenfreemanchina** [comment]
nerver mind~~~ TAT...

**Comment by xiaokaike** [comment]
How do you use it，show the code

**Comment by JounQin** [comment]
@goldenfreemanchina Please upgrade to `0.2.0`, which is a complete rewrite from scratch, which supports `Vue@2.0` and displays `img` tag.

Online DEMO: https://rx-vue.now.sh
